name: LuckyBox
version: 1.0-SNAPSHOT
main: com.github.mhstar331.lucky_box.Main
api-version: 1.21
commands:
  lucky_box:
    description: Lucky Box 플러그인 명령어
    usage: /lucky_box <open|config>
    aliases: [lb]
    subcommands:
      - open
      - config
